In [12]:
# Numpy, Pandas, Matplotlib. etc.
# Numpy - Numerical Python.
# for scientific aplications, modelling, etc.
# linear algebra, computational data science, etc.

# ndarray - data structure.
# N-dimensional array. where N is any number from 0,1,2,3,....

"""
0 dimensions - scalar quantity e.g. 45
1 dimension - vector - magnitude and direction. e.g. x-axis
2 - dimensions - an array of vectors e.g. x- and y- axis
3 - dimensions - an array of 2D vectors having x,y, and z-axis.
4 - Dimensions - an array of 3D vectors
"""

# ndarray is a container of items of the same type.

import numpy as np
zerodim = np.array(45)
onedim = np.array([1,1,3,5,6])

twodim = np.array(
    [
        [1,1,3,5,6],
        [1,1,3,5,6],
        [1,1,3,5,6]
    ]
)

threedim = np.array(
    [
        [[100, 101],[102, 103]],
        [[100, 101],[102, 103]],
        [[100, 101],[102, 103]]
    ]
)

# to determine the number of dimensions of an nd-array, use the ndim property
np.ndim(zerodim)

0

In [3]:
np.ndim(onedim)

1

In [5]:
np.ndim(twodim)

2

In [7]:
np.ndim(threedim)

3

In [9]:
twodim.ndim

2

In [18]:
x = np.array(
    [[67,63,87],
     [77,69,59],
     [44,87,23],
     [12,13,16],
     [59,60,41],
     [68,97,18]
    ]
)


In [13]:
x.ndim

2

In [15]:
# shape property
# shape returns a tuple that show how many rows and columns exist in the array
x.shape

(6, 3)

In [17]:
zerodim.shape


()

In [19]:
onedim.shape

(5,)

In [21]:
twodim.shape

(3, 5)

In [23]:
threedim.shape

(3, 2, 2)

In [25]:
threedim

array([[[100, 101],
        [102, 103]],

       [[100, 101],
        [102, 103]],

       [[100, 101],
        [102, 103]]])

In [20]:
x.shape

(6, 3)

In [31]:
x.reshape(1,18)

array([[67, 63, 87, 77, 69, 59, 44, 87, 23, 12, 13, 16, 59, 60, 41, 68,
        97, 18]])

In [33]:
x.reshape(2, 9)

array([[67, 63, 87, 77, 69, 59, 44, 87, 23],
       [12, 13, 16, 59, 60, 41, 68, 97, 18]])

In [35]:
# only 18 elements so it is wrong.
x.reshape(4,5)

ValueError: cannot reshape array of size 18 into shape (4,5)

In [37]:
# indexing and slicing
onedim

array([1, 1, 3, 5, 6])

In [39]:
onedim[0]

1

In [41]:
onedim[-1]

6

In [43]:
onedim[2] + onedim[3]

8

In [45]:
onedim * 2

array([ 2,  2,  6, 10, 12])

In [47]:
onedim[1:4]

array([1, 3, 5])

In [49]:
x

array([[67, 63, 87],
       [77, 69, 59],
       [44, 87, 23],
       [12, 13, 16],
       [59, 60, 41],
       [68, 97, 18]])

In [51]:
x[2]

array([44, 87, 23])

In [55]:
x[2,1] # row, column notation

87

In [57]:
# slicing
x[:3, 2:]

array([[87],
       [59],
       [23]])

In [59]:
x[:3]

array([[67, 63, 87],
       [77, 69, 59],
       [44, 87, 23]])

In [63]:
x[:3, :2]

array([[67, 63],
       [77, 69],
       [44, 87]])

In [65]:
x[3][2]

16

In [67]:
y = x.reshape(3,6)
y[2,1]

60

In [69]:
x.reshape(3,6)

array([[67, 63, 87, 77, 69, 59],
       [44, 87, 23, 12, 13, 16],
       [59, 60, 41, 68, 97, 18]])